language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r tests-requirements.txt
  - pip install codecov
# command to run tests
script:
  - git config --global user.email "mergeit@localhost"
  - git config --global user.name "mergeit"
  - python -m unittest discover tests
  - codecov
